---
abstract: 'Install the CPAN modules used by andrefs.'
author:
  - 'Andre Santos <andrefs@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-Andrefs
no_index:
  directory:
    - t
    - inc
requires:
  App::pmuninstall: 0
  Biblio::Thesaurus: 0
  Catalyst::Example::Controller::InstantCRUD: 0
  Catalyst::Plugin::Unicode: 0
  DBIx::Class::EncodedColumn: 0
  DBIx::Class::TimeStamp: 0
  DBIx::Migration: 0
  Devel::REPL::Plugin::Colors: 0
  Devel::REPL::Plugin::Commands: 0
  Devel::REPL::Plugin::Completion: 0
  Devel::REPL::Plugin::CompletionDriver::INC: 0
  Devel::REPL::Plugin::CompletionDriver::LexEnv: 0
  Devel::REPL::Plugin::CompletionDriver::Methods: 0
  Devel::REPL::Plugin::DDC: 0
  Devel::REPL::Plugin::DumpHistory: 0
  Devel::REPL::Plugin::FindVariable: 0
  Devel::REPL::Plugin::History: 0
  Devel::REPL::Plugin::LexEnv: 0
  Devel::REPL::Plugin::Nopaste: 0
  Devel::REPL::Plugin::OutputCache: 0
  Devel::REPL::Plugin::Packages: 0
  Devel::REPL::Plugin::ReadLineHistory: 0
  HTML::Auto: 0
  HTML::Entities: 0
  Inline::Files: 0
  Lingua::PT::PLN: 0
  Module::Starter: 0
  MooseX::Types::JSON: 0
  MooseX::Types::Path::Class: 0
  Task::Catalyst::Tutorial: 0
  Task::Dancer: 0
  Task::Kensho: 0
  Task::Kensho::CLI: 0
  Task::Kensho::Config: 0
  Task::Kensho::Dates: 0
  Task::Kensho::Exceptions: 0
  Task::Kensho::Hackery: 0
  Task::Kensho::OOP: 0
  Task::Kensho::Testing: 0
  Task::Kensho::WebDev: 0
  Term::ReadKey: 0
  Term::ReadLine::Perl: 0
  Test::More: 0
  Text::CSV: 0
  Text::RewriteRules: 0
  TheSchwartz::Job: 0
  XML::Entities: 0
  XML::Twig: 0
  corelist: 0
  utf8::all: 0
version: 0.04_01
